### ISSUE TITLE
`nf-core list` fails with `KeyError: 'tag_sha'`

### ISSUE THREAD

**Issue by bounlu** [nf-core/tools#2370] opened 2023-07-12 04:54 UTC
### Description of the bug

`nf-core list` gives the below error:

```
$ nf-core list

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.9 - https://nf-co.re


╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/anaconda3/bin/nf-core:10 in <module>                                                        │
│                                                                                                  │
│    7 from nf_core.__main__ import run_nf_core                                                    │
│    8 if __name__ == '__main__':                                                                  │
│    9 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                        │
│ ❱ 10 │   sys.exit(run_nf_core())                                                                 │
│   11                                                                                             │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/nf_core/__main__.py:110 in run_nf_core                │
│                                                                                                  │
│    107 │   │   │   log.debug(f"Could not check latest version: {e}")                             │
│    108 │   │   stderr.print("\n")                                                                │
│    109 │   # Launch the click cli                                                                │
│ ❱  110 │   nf_core_cli(auto_envvar_prefix="NFCORE")                                              │
│    111                                                                                           │
│    112                                                                                           │
│    113 @click.group(context_settings=dict(help_option_names=["-h", "--help"]))                   │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/click/core.py:1157 in __call__                        │
│                                                                                                  │
│   1154 │                                                                                         │
│   1155 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                           │
│   1156 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1157 │   │   return self.main(*args, **kwargs)                                                 │
│   1158                                                                                           │
│   1159                                                                                           │
│   1160 class Command(BaseCommand):                                                               │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/rich_click/rich_group.py:21 in main                   │
│                                                                                                  │
│   18 │                                                                                           │
│   19 │   def main(self, *args, standalone_mode: bool = True, **kwargs):                          │
│   20 │   │   try:                                                                                │
│ ❱ 21 │   │   │   rv = super().main(*args, standalone_mode=False, **kwargs)                       │
│   22 │   │   │   if not standalone_mode:                                                         │
│   23 │   │   │   │   return rv                                                                   │
│   24 │   │   except click.ClickException as e:                                                   │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/click/core.py:1078 in main                            │
│                                                                                                  │
│   1075 │   │   try:                                                                              │
│   1076 │   │   │   try:                                                                          │
│   1077 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                  │
│ ❱ 1078 │   │   │   │   │   rv = self.invoke(ctx)                                                 │
│   1079 │   │   │   │   │   if not standalone_mode:                                               │
│   1080 │   │   │   │   │   │   return rv                                                         │
│   1081 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!                               │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/click/core.py:1688 in invoke                          │
│                                                                                                  │
│   1685 │   │   │   │   super().invoke(ctx)                                                       │
│   1686 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)                    │
│   1687 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1688 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1689 │   │                                                                                     │
│   1690 │   │   # In chain mode we create the contexts step by step, but after the                │
│   1691 │   │   # base command has been invoked.  Because at that point we do not                 │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/click/core.py:1434 in invoke                          │
│                                                                                                  │
│   1431 │   │   │   echo(style(message, fg="red"), err=True)                                      │
│   1432 │   │                                                                                     │
│   1433 │   │   if self.callback is not None:                                                     │
│ ❱ 1434 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1435 │                                                                                         │
│   1436 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List["CompletionItem"]:  │
│   1437 │   │   """Return a list of completions for the incomplete value. Looks                   │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/click/core.py:783 in invoke                           │
│                                                                                                  │
│    780 │   │                                                                                     │
│    781 │   │   with augment_usage_errors(__self):                                                │
│    782 │   │   │   with ctx:                                                                     │
│ ❱  783 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    784 │                                                                                         │
│    785 │   def forward(                                                                          │
│    786 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # noqa: B902             │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/nf_core/__main__.py:173 in list                       │
│                                                                                                  │
│    170 │   """                                                                                   │
│    171 │   from nf_core.list import list_workflows                                               │
│    172 │                                                                                         │
│ ❱  173 │   stdout.print(list_workflows(keywords, sort, json, show_archived))                     │
│    174                                                                                           │
│    175                                                                                           │
│    176 # nf-core launch                                                                          │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/nf_core/list.py:36 in list_workflows                  │
│                                                                                                  │
│    33 │   wfs = Workflows(filter_by, sort_by, show_archived)                                     │
│    34 │   wfs.get_remote_workflows()                                                             │
│    35 │   wfs.get_local_nf_workflows()                                                           │
│ ❱  36 │   wfs.compare_remote_local()                                                             │
│    37 │   if as_json:                                                                            │
│    38 │   │   return wfs.print_json()                                                            │
│    39 │   else:                                                                                  │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/nf_core/list.py:157 in compare_remote_local           │
│                                                                                                  │
│   154 │   │   │   │   if rwf.full_name == lwf.full_name:                                         │
│   155 │   │   │   │   │   rwf.local_wf = lwf                                                     │
│   156 │   │   │   │   │   if rwf.releases:                                                       │
│ ❱ 157 │   │   │   │   │   │   if rwf.releases[-1]["tag_sha"] == lwf.commit_sha:                  │
│   158 │   │   │   │   │   │   │   rwf.local_is_latest = True                                     │
│   159 │   │   │   │   │   │   else:                                                              │
│   160 │   │   │   │   │   │   │   rwf.local_is_latest = False                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'tag_sha'
```

### Command used and terminal output

```console
$ nf-core list
```

### System information

`$ nextflow info`
  Version: 23.05.0-edge build 5861
  Created: 15-05-2023 04:13 UTC (12:13 SGST)
  System: Linux 5.15.0-72-generic
  Runtime: Groovy 3.0.17 on OpenJDK 64-Bit Server VM 17.0.3-internal+0-adhoc..src
  Encoding: UTF-8 (UTF-8)

**Comment by husensofteng** [comment] 2023-07-12 07:46
I have the same issue even after updating it (thought, still version 2.9):`pip install nf-core --upgrade` 

It might be related to the release the new website!

**Comment by pansapiens** [comment] 2023-07-12 07:57
Is it possible Github changed the output schema of their API (for https://api.github.com/repos/{pipeline}/tags or https://api.github.com/repos/{pipeline}/releases) ?

It seems to work if `"tag_sha"` is changed to `"sha"` here: https://github.com/nf-core/tools/blob/master/nf_core/download.py#L359

**Comment by MatthiasZepper** [comment] 2023-07-12 10:01
@pansapiens: Thanks, very good investigation work!

However, I doubt that changing `tag_sha` to `sha` in Downloads fixes all errors, because the object in which the key changed is queried in `DownloadWorkflow.get_revision_hash()`, but created by `nf_core.list.Workflows()` as `DownloadWorkflow.wfs`

 Inside DownloadWorkflow `wfs` is passed to `get_repo_releases_branches()` to yield
```
   self.pipeline, self.wf_revisions, self.wf_branches = nf_core.utils.get_repo_releases_branches(
                self.pipeline, self.wfs
            )
```

Therefore, I think the root cause is to be found in `nf_core.list.Workflows.get_remote_workflows()` and specifically the queried JSON [https://nf-co.re/pipelines.json](https://nf-co.re/pipelines.json), where the `tag_sha` field was renamed to `sha` in the workflow.releases.

**Comment by mashehu** [comment] 2023-07-12 10:17
Sorry, I guess it is my fault. 
I will uödaye it on the website repo, where this file is created.

**Comment by MatthiasZepper** [comment] 2023-07-12 12:09
If the website uses consistently `sha`, I have no objections against changing it in tools. But I agree that as a kind of hot fix, we should have an old-style `pipelines.json` for now, until we are ready to release a new tools version? 

How much do you have to change on the website to revert `sha` to `tag_sha`? Is it just a small tweak in the JSON export, or does this also entail changing e.g. the components used in the pipeline pages?

**Comment by mashehu** [comment] 2023-07-12 12:11
not too much. PR is building as we speak

**Comment by mashehu** [comment] 2023-07-13 08:07
fixed with https://github.com/nf-core/website/pull/1856

**Closed by mashehu** 2023-07-13 08:07 UTC
Labels: bug
