### ISSUE TITLE
subworkflow command: update

### ISSUE THREAD

**Issue by matthdsm** [nf-core/tools#1950] opened 2022-10-14 09:21 UTC
### Description of feature

Hi,

Is it possilble to also add `nf-core subworkflows update`. Currently, this is solved by force reinstalling, but update would be "nicer".

Thanks
M

**Comment by maxulysse** [comment] 2022-10-14 11:03
👍
I tried that command this morning, was definitely missing

**Comment by mashehu** [comment] 2022-10-14 22:30
Duplicate of #1892. But I see the demand for it 🙂

**Closed by mashehu** 2022-10-14 22:30 UTC
Labels: enhancement, subworkflows
