### ISSUE TITLE
Clarify the usage of --skip-bbsplit parameter (https://github.com/nf-core/rnaseq/issues/762)

### ISSUE THREAD

**Issue by G-Sarah** [nf-core/tools#1460] opened 2022-03-16 13:14 UTC

**Comment by ewels** [comment] 2022-03-23 12:47
Not sure what this issue is? Seems to be a duplicate of https://github.com/nf-core/rnaseq/issues/762 ? Closing.. 😄

**Closed by ewels** 2022-03-23 12:47 UTC
