### ISSUE TITLE
nf-core modules create tool/subtool should make a main.nf in a subfolder of subtool in pipelines

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/tools#3251] opened 2024-10-25 08:13 UTC
### Description of feature

When writing local pipeline modules, using `nf-core modules create tool/subtool`, it follows a different file structure to the standard modules file structure.
It would be nice if local pipeline modules followed the same file format as nf-core modules.

Rather than
```
modules/
    local/
        tool/
            subtool.nf
```
It should be
```
modules/
    local/
        tool/
            subtool/
                main.nf
```

The `environment.yml` is also missing as a result of this. 

## Alternative

Turn everything on it's head in nf-core modules and each module should be in a subtool.nf file, meaning only a single (all encompassing) environment.yml is needed for all subtools ( which also rearranges tests, etc )

**Comment by mirpedrol** [comment] 2024-10-25 08:19
Hi @mahesh-panchal, thanks for the issue! This is a duplicate of https://github.com/nf-core/tools/issues/1929 and it's already in the roadmap 🙂

**Closed** 2024-10-25 08:58 UTC
Labels: enhancement
