### ISSUE TITLE
Make 'nf-core bump-version' leave indents alone

### ISSUE THREAD

**Issue by pinin4fjords** [nf-core/tools#2513] opened 2023-11-13 09:27 UTC
### Description of the bug

I see a lot of comments like https://github.com/nf-core/mag/pull/541/files#r1390783670, and consistently forget to fix my own indents after a version bump. 

Basically what we'd want to happen is:

```
...
    nextflowVersion = '!>=23.04.0'
    version         = '2.5.0'
...
```

... going to something like:

```
...
    nextflowVersion = '!>=23.04.0'
    version         = 2.5.1'
...
```

... but what we actually get is:

```
...
    nextflowVersion = '!>=23.04.0'
    version = '2.5.1'
...
```

It would be good to have that command leave the indent alone and just bump the value.

### Command used and terminal output

```console
$ nf-core bump-version
```

**Comment by maxulysse** [comment] 2023-11-13 10:38
duplicate of #2499

**Closed by maxulysse** 2023-11-13 10:38 UTC
Labels: bug

**Comment by maxulysse** [comment] 2023-11-13 10:44
and duplicate of #2206
