### ISSUE TITLE
`nf-core bump-version` does not respect previous formatting

### ISSUE THREAD

**Issue by fabianegli** [nf-core/tools#2499] opened 2023-11-02 17:03 UTC
### Description of the bug

`nf-core bump-version` does not respect previous formatting.

The diff is

```
           - version         = '1.2.0'
           + version = '1.3.0dev'
```

but I would expect it to be 

```
           - version         = '1.2.0'
           + version         = '1.3.0dev'
```

### Command used and terminal output

```console
% nf-core bump-version 1.3.0dev
...
           - version         = '1.2.0'
           + version = '1.3.0dev'
```

**Comment by maxulysse** [comment] 2023-11-13 10:39
duplicate of #2206

**Closed by maxulysse** 2023-11-13 10:39 UTC
Labels: bug
