### ISSUE TITLE
nf-core lint throws No such file or directory: 'pre-commit -->with solution!

### ISSUE THREAD

**Issue by WackerO** [nf-core/tools#2129] opened 2022-12-15 12:12 UTC
### Description of the bug

Hello, after doing a template update of my nextflow pipeline (not nf-core, but written with the nf-core template), the command `nf-core lint` throws the following error:                                        
```
FileNotFoundError: [Errno 2] No such file or directory: 'pre-commit'
```
I am using nf-core as a conda/mamba installation. I was able to solve this by manually installing pre-commit like so:
`mamba install -c conda-forge pre-commit`
Maybe this can be added as dependency of nf-core so that the package is auto-installed?

### Command used and terminal output

```console
nf-core lint

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.7.1 - https://nf-co.re


INFO     Recomputing commit SHA for module 'modules/custom/dumpsoftwareversions' which was missing from 'modules.json'                                                 
╭───────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────╮
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/bin/nf-core:10 in <module>                                                                                    │
│                                                                                                                                                                     │
│    9 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                                                                                           │
│ ❱ 10 │   sys.exit(run_nf_core())                                                                                                                                    │
│   11                                                                                                                                                                │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/nf_core/__main__.py:105 in run_nf_core                                            │
│                                                                                                                                                                     │
│    104 │   # Launch the click cli                                                                                                                                   │
│ ❱  105 │   nf_core_cli(auto_envvar_prefix="NFCORE")                                                                                                                 │
│    106                                                                                                                                                              │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/click/core.py:1130 in __call__                                                    │
│                                                                                                                                                                     │
│   1129 │   │   """Alias for :meth:`main`."""                                                                                                                        │
│ ❱ 1130 │   │   return self.main(*args, **kwargs)                                                                                                                    │
│   1131                                                                                                                                                              │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/rich_click/rich_group.py:21 in main                                               │
│                                                                                                                                                                     │
│   20 │   │   try:                                                                                                                                                   │
│ ❱ 21 │   │   │   rv = super().main(*args, standalone_mode=False, **kwargs)                                                                                          │
│   22 │   │   │   if not standalone_mode:                                                                                                                            │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/click/core.py:1055 in main                                                        │
│                                                                                                                                                                     │
│   1054 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                                                                                     │
│ ❱ 1055 │   │   │   │   │   rv = self.invoke(ctx)                                                                                                                    │
│   1056 │   │   │   │   │   if not standalone_mode:                                                                                                                  │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/click/core.py:1657 in invoke                                                      │
│                                                                                                                                                                     │
│   1656 │   │   │   │   with sub_ctx:                                                                                                                                │
│ ❱ 1657 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                  │
│   1658                                                                                                                                                              │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/click/core.py:1404 in invoke                                                      │
│                                                                                                                                                                     │
│   1403 │   │   if self.callback is not None:                                                                                                                        │
│ ❱ 1404 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                                                                                   │
│   1405                                                                                                                                                              │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/click/core.py:760 in invoke                                                       │
│                                                                                                                                                                     │
│    759 │   │   │   with ctx:                                                                                                                                        │
│ ❱  760 │   │   │   │   return __callback(*args, **kwargs)                                                                                                           │
│    761                                                                                                                                                              │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/click/decorators.py:26 in new_func                                                │
│                                                                                                                                                                     │
│    25 │   def new_func(*args, **kwargs):  # type: ignore                                                                                                            │
│ ❱  26 │   │   return f(get_current_context(), *args, **kwargs)                                                                                                      │
│    27                                                                                                                                                               │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/nf_core/__main__.py:357 in lint                                                   │
│                                                                                                                                                                     │
│    356 │   try:                                                                                                                                                     │
│ ❱  357 │   │   lint_obj, module_lint_obj = nf_core.lint.run_linting(                                                                                                │
│    358 │   │   │   dir,                                                                                                                                             │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/nf_core/lint/__init__.py:89 in run_linting                                        │
│                                                                                                                                                                     │
│    88 │   # Create the modules lint object                                                                                                                          │
│ ❱  89 │   module_lint_obj = nf_core.modules.lint.ModuleLint(pipeline_dir,                                                                                           │
│       hide_progress=hide_progress)                                                                                                                                  │
│    90                                                                                                                                                               │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/nf_core/modules/lint/__init__.py:91 in __init__                                   │
│                                                                                                                                                                     │
│    90 │   │   │   modules_json = ModulesJson(self.dir)                                                                                                              │
│ ❱  91 │   │   │   modules_json.check_up_to_date()                                                                                                                   │
│    92 │   │   │   self.all_remote_modules = []                                                                                                                      │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/nf_core/modules/modules_json.py:608 in check_up_to_date                           │
│                                                                                                                                                                     │
│    607 │   │                                                                                                                                                        │
│ ❱  608 │   │   self.dump()                                                                                                                                          │
│    609                                                                                                                                                              │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/nf_core/modules/modules_json.py:1029 in dump                                      │
│                                                                                                                                                                     │
│   1028 │   │   │   fh.write("\n")                                                                                                                                   │
│ ❱ 1029 │   │   run_prettier_on_file(self.modules_json_path)                                                                                                         │
│   1030                                                                                                                                                              │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/site-packages/nf_core/lint_utils.py:68 in run_prettier_on_file                                  │
│                                                                                                                                                                     │
│   67 │   try:                                                                                                                                                       │
│ ❱ 68 │   │   subprocess.run(                                                                                                                                        │
│   69 │   │   │   ["pre-commit", "run", "--config", nf_core_pre_commit_config, "prettier",                                                                           │
│      "--files", file],                                                                                                                                              │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/subprocess.py:505 in run                                                                        │
│                                                                                                                                                                     │
│    504 │                                                                                                                                                            │
│ ❱  505 │   with Popen(*popenargs, **kwargs) as process:                                                                                                             │
│    506 │   │   try:                                                                                                                                                 │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/subprocess.py:951 in __init__                                                                   │
│                                                                                                                                                                     │
│    950 │   │   │                                                                                                                                                    │
│ ❱  951 │   │   │   self._execute_child(args, executable, preexec_fn, close_fds,                                                                                     │
│    952 │   │   │   │   │   │   │   │   pass_fds, cwd, env,                                                                                                          │
│                                                                                                                                                                     │
│ /home-link/iivow01/tools/miniconda3/envs/nfcore_stuff/lib/python3.9/subprocess.py:1821 in _execute_child                                                            │
│                                                                                                                                                                     │
│   1820 │   │   │   │   │   │   err_msg = os.strerror(errno_num)                                                                                                     │
│ ❱ 1821 │   │   │   │   │   raise child_exception_type(errno_num, err_msg, err_filename)                                                                             │
│   1822 │   │   │   │   raise child_exception_type(err_msg)                                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 'pre-commit'
```

### System information

- nextflow version 22.10.2.5832
- Desktop
- local
- Rocky Linux
- nf-core/tools version 2.7.1
- python 3.9.15

**Comment by fabianegli** [comment] 2022-12-15 13:46
The problem is, that the [bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nf-core/meta.yaml) was not yet updated to reflect the changes in dependencies for the latest release.

**Comment by fabianegli** [comment] 2022-12-15 13:49
Linking this here for easier access: https://github.com/bioconda/bioconda-recipes/pull/38423

**Comment by fabianegli** [comment] 2022-12-15 18:59
Closing because the issue has been resolved (checked by testing with a local conda install).

**Comment by fabianegli** [comment] 2022-12-15 19:00
@WackerO thank you for reporting the issue! :-)

**Closed by fabianegli** 2022-12-15 18:59 UTC
Labels: bug
