### ISSUE TITLE
Docker UID Defaults

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#336] opened 2019-05-16 14:13 UTC
We should probably think about adding this here as default to the Docker scope:

```nextflow
docker.enabled = true
fixOwnership = true
runOptions = "-u \$(id -u):\$(id -g)"
```

**Comment by matq007** [comment] 2019-05-16 14:46
Also, most of the clusters are cunning CentOS which requires `z` parameter as well for docker.
`mountFlags = 'z'`

**Comment by apeltzer** [comment] 2019-05-17 10:42
Do you guys use Docker on a cluster? We cannot due that for "security reasons" here. Also, does that then work for everyone? I know that the fixOwnership and runOptions stuff will work pretty much everywhere (?) while the mountFlags might not (?)

**Comment by matq007** [comment] 2019-05-17 10:49
We have isolated cluster where we have a docker. We are using local executor and the only way to actually run it correctly (CentOS security policy) I had to enable the mountFlags to `z`. It is also mentioned in the docs of [nextflow](https://www.nextflow.io/docs/latest/config.html#scope-docker).

**Comment by ewels** [comment] 2019-05-18 13:38
I don't think that it should go in the template base config unless it works for everyone (at least, doesn't break stuff for those that don't need it). But why does nextflow itself not have these as defaults if that's the case?

**Comment by apeltzer** [comment] 2019-05-20 07:15
Good question - @pditommaso can you share some insights on why this is not the "default" behaviour?

**Comment by pditommaso** [comment] 2019-05-20 10:27
Good point, that was planned https://github.com/nextflow-io/nextflow/issues/515. It was never merged because it could introduce a breaking change caused by the fact that `-u` alters the user `HOME` variable, tho rarely it could be a problem.  

Maybe it's time to give it a try.

**Comment by gongyixiao** [comment] 2019-08-15 17:18
> it could introduce a breaking change caused by the fact that `-u` alters the user `HOME` variable, tho rarely it could be a problem.

This causes problem when running Spark in Docker.
https://github.com/nextflow-io/nextflow/issues/515#issuecomment-521715925

**Comment by ewels** [comment] 2019-10-05 21:57
`runOptions` added to the template in https://github.com/nf-core/tools/pull/352

`fixOwnership` isn't added (yet) - does that need to be there as well?

**Comment by apeltzer** [comment] 2019-10-06 12:03
I think not no

**Comment by MaxUlysse** [comment] 2019-12-17 13:48
How important is it to keep this `runOptions = "-u \$(id -u):\$(id -g)"`?
It's making impossible to enable GATK Spark cf https://github.com/nf-core/sarek/pull/76

**Comment by apeltzer** [comment] 2019-12-17 13:53
I never had issues without it - so maybe it’s not required. We had people who had to use it though, which is something we should document / state in troubleshooting on the webpage maybe ?

**Comment by MaxUlysse** [comment] 2019-12-17 13:57
Anyhow, I'll be removing that for Sarek, I'll keep everyone updated if any issue arise.

**Closed** 2020-11-25 13:37 UTC
Labels: template
