### ISSUE TITLE
nf-core install error

### ISSUE THREAD

**Issue by jjfarrell** [nf-core/tools#1122] opened 2021-06-22 00:38 UTC
## Description of the bug

The command line:
The installation command:
`conda create --name nf-core nf-core  python=3.7 nextflow`
fails to install the conda environment. Other python versions have been specified with the same result. 
## Steps to reproduce

Steps to reproduce the behaviour:

```
conda create --name nf-core nf-core  python=3.7 nextflow

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.                                                                                                                                                       failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package curl conflicts for:
nf-core -> git -> curl
nextflow -> curl[version='>=7.59.0,<8.0a0|>=7.64.1,<8.0a0|>=7.71.1,<8.0a0|>=7.76.0,<8.0a0|>=7.76.1,<8.0a0']

Package openssl conflicts for:
python=3.7 -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a']
nextflow -> curl -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a']
nf-core -> git -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.0.2l,<1.0.3a']

Package python conflicts for:
nf-core -> python
python=3.7
nf-core -> click -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|>=3.5|>=3.4|>=3|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|<4.0']
```

## Expected behaviour

The nf-core conda environment is created

**Comment by ewels** [comment] 2021-06-24 12:55
Hi @jjfarrell,

This is odd, there should be no incompatibility here. Indeed, these are exactly the versions that I run locally.

Could you please try again with `mamba`? That usually gives much more useful error messages.

```bash
conda install mamba
mamba create --name nf-core nf-core  python=3.7 nextflow
```

What happens if you create a new environment and then install the tools separately?

```bash
conda create --name nf-core
conda install python=3.7
conda install nf-core
conda install nextflow
```

Note that Python needs to be installed first - I wonder if it's this order of package names that could be causing an issue?

Phil

**Comment by jjfarrell** [comment] 2021-06-26 22:14
This did work using anaconda 4.5.4 but not with miniconda/4.9.2: 
conda create --name nf-core
conda install python=3.7
conda install nf-core
conda install nextflow

But in the process the anaconda 4.5.4 generated the following message: 

The following packages will be DOWNGRADED:

    python:             3.7.10-h12debd9_4                 --> 3.6.13-h12debd9_1

```
(base) [farrell@scc-hadoop gatk]$ source activate nf-core
(nf-core) [farrell@scc-hadoop gatk]$ conda install python=3.7
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.4
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /usr3/bustaff/farrell/.conda/envs/nf-core

  added / updated specs:
    - python=3.7


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main
    _openmp_mutex:    4.5-1_gnu
    ca-certificates:  2021.5.25-h06a4308_1
    certifi:          2021.5.30-py37h06a4308_0
    ld_impl_linux-64: 2.35.1-h7274673_9
    libffi:           3.3-he6710b0_2
    libgcc-ng:        9.3.0-h5101ec6_17
    libgomp:          9.3.0-h5101ec6_17
    libstdcxx-ng:     9.3.0-hd4cf53a_17
    ncurses:          6.2-he6710b0_1
    openssl:          1.1.1k-h27cfd23_0
    pip:              21.1.2-py37h06a4308_0
    python:           3.7.10-h12debd9_4
    readline:         8.1-h27cfd23_0
    setuptools:       52.0.0-py37h06a4308_0
    sqlite:           3.36.0-hc218d9a_0
    tk:               8.6.10-hbc83047_0
    wheel:            0.36.2-pyhd3eb1b0_0
    xz:               5.2.5-h7b6447c_0
    zlib:             1.2.11-h7b6447c_3

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(nf-core) [farrell@scc-hadoop gatk]$ conda install nf-core
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.4
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /usr3/bustaff/farrell/.conda/envs/nf-core

  added / updated specs:
    - nf-core


The following NEW packages will be INSTALLED:

    arrow:              0.13.1-py36_0
    attrs:              21.2.0-pyhd3eb1b0_0
    binaryornot:        0.4.4-pyhd3eb1b0_1
    brotlipy:           0.7.0-py36h27cfd23_1003
    cffi:               1.14.5-py36h261ae71_0
    chardet:            4.0.0-py36h06a4308_1003
    click:              8.0.1-pyhd3eb1b0_0
    cookiecutter:       1.7.2-pyhd3eb1b0_0
    cryptography:       3.4.7-py36hd23ed53_0
    expat:              2.4.1-h2531618_2
    git:                2.23.0-pl526hacde149_0
    gitdb:              4.0.7-pyhd3eb1b0_0
    gitpython:          3.1.18-pyhd3eb1b0_1
    idna:               2.10-pyhd3eb1b0_0
    importlib-metadata: 3.10.0-py36h06a4308_0
    importlib_metadata: 3.10.0-hd3eb1b0_0
    jinja2:             2.11.3-pyhd3eb1b0_0
    jinja2-time:        0.2.0-pyhd3eb1b0_2
    jsonschema:         3.2.0-py_2
    krb5:               1.18.2-h173b8e3_0
    libcurl:            7.71.1-h20c2e04_1
    libedit:            3.1.20210216-h27cfd23_1
    libssh2:            1.9.0-h1ba5d50_1
    markupsafe:         1.1.1-py36h7b6447c_0
    nf-core:            1.9-py_0                 bioconda
    pcre:               8.45-h295c915_0
    perl:               5.26.2-h14c3975_0
    poyo:               0.5.0-pyhd3eb1b0_0
    pycparser:          2.20-py_2
    pyopenssl:          20.0.1-pyhd3eb1b0_1
    pyrsistent:         0.17.3-py36h7b6447c_0
    pysocks:            1.7.1-py36h06a4308_0
    python-dateutil:    2.8.1-pyhd3eb1b0_0
    python-slugify:     5.0.2-pyhd3eb1b0_0
    pyyaml:             5.4.1-py36h27cfd23_1
    requests:           2.25.1-pyhd3eb1b0_0
    requests-cache:     0.4.10-py36_0            bioconda
    six:                1.16.0-pyhd3eb1b0_0
    smmap:              4.0.0-pyhd3eb1b0_0
    tabulate:           0.8.9-py36h06a4308_0
    text-unidecode:     1.3-py_0
    typing-extensions:  3.7.4.3-hd3eb1b0_0
    typing_extensions:  3.7.4.3-pyh06a4308_0
    unidecode:          1.2.0-pyhd3eb1b0_0
    urllib3:            1.26.4-pyhd3eb1b0_0
    whichcraft:         0.6.1-pyhd3eb1b0_0
    yaml:               0.2.5-h7b6447c_0
    zipp:               3.4.1-pyhd3eb1b0_0

The following packages will be UPDATED:

    certifi:            2021.5.30-py37h06a4308_0          --> 2021.5.30-py36h06a4308_0
    pip:                21.1.2-py37h06a4308_0             --> 21.1.2-py36h06a4308_0
    setuptools:         52.0.0-py37h06a4308_0             --> 52.0.0-py36h06a4308_0
    wheel:              0.36.2-pyhd3eb1b0_0               --> 0.36.2-pyhd3eb1b0_0

The following packages will be DOWNGRADED:

    python:             3.7.10-h12debd9_4                 --> 3.6.13-h12debd9_1

Proceed ([y]/n)?

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(nf-core) [farrell@scc-hadoop gatk]$ conda install nextflow
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.4
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /usr3/bustaff/farrell/.conda/envs/nf-core

  added / updated specs:
    - nextflow


The following NEW packages will be INSTALLED:

    coreutils: 8.25-1             bioconda
    curl:      7.71.1-hbc83047_1
    libgcc:    7.2.0-h69d50b8_2
    nextflow:  20.10.0-hecda079_0 bioconda
    openjdk:   8.0.152-h7b6447c_3

Proceed ([y]/n)? yes

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

With miniconda, If instead of using the python=3.7 but kept the base python (3.9.5) it worked fine. 

 installed it with the commands:
```
module load  miniconda/4.9.2
conda create --name nf-core nf-core nextflow
```

Mamba also worked (but much faster) ....
```
module load  miniconda/4.9.2
conda create --name nf-core
 mamba install python=3.7 nf-core nextflow
```

**Comment by apeltzer** [comment] 2022-03-08 10:49
I might be wrong here, but it looks like you _create_ the nf-core environment but do not activate it before you install python + nf-core + nextflow. This means, it will do that in your `base`. I just tried reproducing this in a clean environment and this all worked flawlessly:

```
conda create -n nf-core-test-issue-1122
conda activate nf-core-test-issue-1122
mamba install python=3.7 nf-core nextflow
```

And looks all good to me: 

![image](https://user-images.githubusercontent.com/2359510/157223659-612532ed-68e7-41c5-92b5-2224b6107472.png)

I will therefore close this as it doesn't look like its an issue with nf-core itself but rather with  the packages not being installed in the clean environment which you'd need to _activate_ before installing the other packages you wanted ot use. Also: If you keep these in a separate environment anyways, you don't have to restrict to python=3.7 and can just do a `mamba install nf-core nextflow` and let mamba figure out which python version to use in the env.

**Closed by apeltzer** 2022-03-08 10:49 UTC
Labels: bug
