### ISSUE TITLE
Linting: Anaconda API fails for some packages 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#231] opened 2018-11-22 18:27 UTC
```
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-rmarkdown=1.10
  http://nf-co.re/errors#8: Conda dependency had an unknown version: fasttree=2.1.10
  http://nf-co.re/errors#8: Conda dependency had an unknown version: mafft=7.310
  http://nf-co.re/errors#8: Conda dependency had an unknown version: vsearch=2.7.0
  http://nf-co.re/errors#8: Conda dependency had an unknown version: bleach=2.1.3
  http://nf-co.re/errors#8: Conda dependency had an unknown version: emperor=1.0.0beta16
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-bh=1.66.0_1
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-data.table=1.11.4
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-digest=0.6.15
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-futile.logger=1.4.3
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-lambda.r=1.2
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-matrixstats=0.53.1
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-rcppparallel=4.4.0
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-scales=0.5.0
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-snow=0.4_2
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-stringr=1.3.0
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-tibble=1.4.2
  http://nf-co.re/errors#8: Conda dependency had an unknown version: r-viridislite=0.3.0
  http://nf-co.re/errors#8: Conda dependency had an unknown version: urllib3=1.23
  http://nf-co.re/errors#8: Conda dependency had an unknown version: q2-deblur=2018.6.0
```

Pinging in @sven1103 and @ewels do you guys have an idea?

**Comment by ewels** [comment] 2018-12-13 12:39
That is an insane number of software dependencies. Where are there so many??

And not sure what the problem is here. Can't you just update all of the out of date ones? The not-found ones presumably don't match known releases on the anaconda API so may need more investigation.

**Comment by ewels** [comment] 2018-12-13 12:40
If the unknown version ones definitely do exist with those version numbers, then it could be that the API is complaining because we're hitting it with so many requests. May be worth escalating the exception in the code that is being handled here to see what the actual error is.

**Comment by ewels** [comment] 2019-01-03 10:06
Should hopefully be fixed with the next release of tools. Closing now, can reopen if stuff still fails after that.

**Closed by ewels** 2019-01-03 10:06 UTC
Labels: linting

**Comment by apeltzer** [comment] 2019-01-03 10:16
That should also give us a failure-free release for the `ampliseq` pipeline :-)
